// Generated by https://quicktype.io

export interface CategoriesResponse {
  total:      number;
  categorias: Category[];
}

export interface Category {
  _id:     string;
  nombre:  string;
  usuario?: CreatedBy;
}

export interface CreatedBy {
  _id:    string;
  nombre: string;
}
